[build]
  publish = "build"
  functions = "netlify/functions"

[dev]
  framework = "create-react-app"
  targetPort = 3000  # Assuming your React app runs on port 3000
  port = 8888  # Port used by Netlify Dev

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  

[[redirects]]
from = "/*"
to = "/index.html"
status = 200