[build]
  publish = "build"                # Directory to publish for deployment
  functions = "netlify/functions"  # Directory for serverless functions

[dev]
  framework = "create-react-app"   # Framework being used for development
  targetPort = 3000                # Port where the React app runs
  port = 8888                      # Port used by Netlify Dev

[[redirects]]
  from = "/api/*"                  # Redirect all API requests
  to = "/.netlify/functions/server/:splat"  # to the serverless function handler
  status = 200

[[redirects]]
  from = "/*"                      # Redirect all other requests
  to = "/index.html"               # to the React app entry point (single-page app)
  status = 200

[context.production.environment]
  NODE_ENV = "production"          # Set NODE_ENV to 'production' for optimized builds